spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: dell81639
        url: jdbc:postgresql://192.168.10.101:5432/erpweb
        
